version: '3.7'
services:
  postgres:
    image: postgres:11.3
    networks:
      - backend

  influx:
    image: influxdb:1.5.4
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=monitoring
      - INFLUXDB_ADMIN_PASSWORD=monitoring
    networks:
      - backend

  grafana:
    build:
      context: .
      dockerfile: Dockerfile-grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influx
    environment:
      - GF_SECURITY_ADMIN_USER=monitoring
      - GF_SECURITY_ADMIN_PASSWORD=monitoring
    networks:
      - backend

  web:
    build: .
    volumes:
      - .:/home
    ports:
      - 80:3000
    command: rails s -b 0.0.0.0 -p 3000
    depends_on:
      - postgres
      - influx
      - grafana
    env_file:
      - .env
    networks:
      - backend
      - frontend

networks:
  frontend:
    external: true
  backend:
    external: false
volumes:
  influxdb-storage:
  grafana-storage:
  grafana-provisioning:
