default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  port: 5432
  username: <%= ENV['PG_DATABASE_USER'] %>
  password: <%= ENV['PG_DATABASE_PASSWORD'] %>
  timeout: 5000

development:
  <<: *default
  database: smart_tree_server_development

test:
  <<: *default
  database: smart_tree_server_test

production:
  <<: *default
database: smart_tree_server_production
